#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Allow bck-i-search.
bindkey -v
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -d $HOME/.local/bin ]]; then
  export PATH=$HOME/.local/bin:$PATH:
  export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
else
  export PATH=$PATH
fi

if [[ -d /usr/X11/bin ]]; then
  export PATH=$PATH:/usr/X11/bin
fi


export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel/python
if [[ -f /usr/local/bin/python3 ]]; then
  export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
else
  export VIRTUALENVWRAPPER_PYTHON=$HOME/.local/bin/python3
fi
if [[ -f /usr/local/bin/virtualenvwrapper.sh ]]; then
  source /usr/local/bin/virtualenvwrapper.sh
else
  source $HOME/.local/bin/virtualenvwrapper.sh
fi

if [[ -f $HOME/.xmodmap-$(uname -n) ]]; then
  xmodmap $HOME/.xmodmap-$(uname -n)
fi

fpath=($HOME/.zprezto/modules/completion/external/src $fpath)
