#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Allow bck-i-search.
bindkey -v
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Includes Android SDK Support for mobile developers
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$HOME/.local/bin:/usr/local/bin:$PATH:/usr/X11/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools


fpath=($HOME/.zprezto/modules/completion/external/src $fpath)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Secret configs
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/secret.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/secret.zsh"
fi